DROP TABLE IF EXISTS estandares.nanda_noc CASCADE;
CREATE TABLE IF NOT EXISTS estandares.nanda_noc ( 
    id SERIAL PRIMARY KEY, 
    nombre TEXT NOT NULL, 
    version TEXT NOT NULL, 
    deleted BOOLEAN DEFAULT FALSE 
);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Aceptación: estado de la salud', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Aclaración de toxinas sistémicas: diálisis', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Adaptación a la discapacidad física', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Adaptación al traslado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Adaptación del cuidador principal al ingreso del paciente en un centro sanitario', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Adaptación del niño a la hospitalización', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Adaptación del prematuro', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Adaptación del recién nacido', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Afrontamiento de los problemas de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Afrontamiento de problemas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Alfabetización económica ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Alteración del estilo de vida del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Ambiente seguro del hogar ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Ambular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Ambular: silla de ruedas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Apetito', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Apoyo familiar durante el tratamiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Atención al lado afectado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: accidente cerebrovascular ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontol: alergia conocida ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: anemia crónica ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: arritmia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: artritis ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: asma', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontro: cáncer ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: diabetes', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad aguda', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad arterial coronaria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad arterial periférica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad celiaca (celiaquía) ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad crónica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad inflamatoria intestinal ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad pulmonar obstructiva crónica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: enfermedad renal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: esclerosis múltiple', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: herida', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: infección ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: insuficiencia cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: linfedema ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values (' Autocontrol: neumonía ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: osteoporosis', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: trastorno del espectro autista ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: trastorno lipídico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: tratamiento anticoagulante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol: virus de la inmunodeficiencia humana (VIH) ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de la agresión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de la ansiedad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de la conducta abusiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de la depresión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de la ira', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de la mutilación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de las convulsiones', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol de los impulsos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol del impulso suicida', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol del miedo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol del pánico ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol del pensamiento distorsionado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocontrol del trastorno de la alimentación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidado de la ostomía', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: actividades de la vida diaria (AVD)', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: actividades instrumentales de la vida diaria (AIVD)', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: baño', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: comer', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: higiene', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: higiene oral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: medicación no parenteral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: medicación parenteral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: uso del inodoro', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autocuidados: vestir', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autoestima', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autogestión de las actividades instrumentales de la vida diaria (AIVD) ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autogestión de los cuidados', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Autonomía personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Bienestar del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Bienestar personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Caídas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Calidad de vida', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Cese de la desatención', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Cese del abuso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Clima social de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Coagulación sanguínea', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Cognición', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Competencia social', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Comportamiento de alfabetización en salud ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Compromiso del paciente ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Comunicación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Comunicación: expresiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Comunicación: receptiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Concentración', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conciencia de uno mismo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de abandono del consumo de alcohol', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de abandono del consumo de drogas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de abandono del consumo de tabaco', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de adhesión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de adhesión: dieta saludable', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de aumento de peso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de búsqueda de la salud', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de compensación auditiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de compensación visual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de cumplimiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de cumplimiento: actividad prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de cumplimiento: dieta prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de cumplimiento: medicación prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de fomento de la salud', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de la salud maternal en el postparto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de mantenimiento del peso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de pérdida de peso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta de prevención de caídas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta personal de detección precoz de enfermedades', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conducta sanitaria prenatal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conductas de seguridad personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conductas de vacunación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: actividad prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: alimentación con biberón', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: alimentación con taza', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: conducta sanitaria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: conservación de la energía', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: control de la diabetes', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: control de la enfermedad cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: control de la hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: control de la infección', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: control del consumo de sustancias', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: cuidado de los hijos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: cuidados de la ostomía', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: cuidados del lactante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: cuidados del recién nacido pretérmino', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: dieta prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: dieta saludable', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: estilo de vida saludable', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: fomento de la fertilidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: funcionamiento sexual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: funcionamiento sexual durante el embarazo y el postparto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: gestación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: gestión del tiempo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: lactancia materna', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de heridas ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la alergia ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la anemia crónica ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la arritmia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la artritis', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la demencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la depresión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad aguda', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad arterial coronaria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad arterial periférica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad celiaca ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad cerebrovascular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad crónica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad inflamatoria intestinal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad pulmonar obstructiva crónica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la enfermedad renal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la epilepsia ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la esclerosis múltiple', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la insuficiencia cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la neumonía', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo de la osteoporosis', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del asma', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del cáncer', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del estrés', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del linfedema ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del peso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del trastorno de la alimentación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del trastorno del espectro autista ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del trastorno lipídico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del tratamiento anticoagulante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: manejo del virus de la inmunodeficiencia humana ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: mecanismos corporales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: medicación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: parto y alumbramiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: prevención de caídas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: prevención del embarazo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: procedimiento terapéutico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: procedimientos diagnósticos y terapéuticos ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: proceso de la enfermedad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: recursos sanitarios', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: reducción de la amenaza de accidente cerebrovascular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: reducción de la amenaza del cáncer', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: reducción de la amenaza de trombo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: régimen terapéutico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: rehabilitación cardiaca ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: rehabilitación musculoesquelética ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: salud materna en el puerperio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: salud materna en la preconcepción', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: seguridad física infantil', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conocimiento: seguridad personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Consecuencias de la adicción a sustancias psicoactivas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Consecuencias de la inmovilidad: fisiológicas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Consecuencias de la inmovilidad: psicocognitivas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Conservación de la energía', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Continencia intestinal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Continencia urinaria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control de náuseas y vómitos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control de síntomas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: accidente cerebrovascular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: acoso infantil ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: alergias infantiles ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: aspiración ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: caídas ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: cáncer', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: consumo de alcohol', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: consumo de drogas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: consumo de tabaco', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: deshidratación ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: deterioro auditivo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: deterioro visual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: embarazo no deseado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: enfermedad cardiovascular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: enfermedades de transmisión sexual (ETS)', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: exposición al sol', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: herida por presión (úlcera por presión) ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: hipertermia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: hipotensión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: hipotermia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: obesidad ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: ojo seco', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: osteoporosis', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: peligros medioambientales ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: proceso infeccioso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: trastorno lipídico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo: trombos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo familiar: acoso ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo familiar: obesidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: acoso infantil ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: enfermedad crónica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: enfermedad transmisible', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: exposición al plomo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: obesidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: peligros medioambientales ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: suicidio ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: tradiciones culturales no saludables', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Control del riesgo social: violencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Crecimiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Creencias sobre la salud', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Creencias sobre la salud: capacidad percibida para actuar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Creencias sobre la salud: percepción de amenaza', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Creencias sobre la salud: percepción de control', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Creencias sobre la salud: percepción de recursos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Curación de la herida: por primera intención', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Curación de la herida: por segunda intención', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Curación de las quemaduras', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Curación ósea', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Deambulación segura', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo: adulto de mediana edad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo: adulto joven', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo: adulto mayor', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 1 mes', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 2 meses', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 4 meses', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 6 meses', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 12 meses', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 2 años', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 3 años', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 4 años', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: 5 años', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: segunda infancia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desarrollo infantil: adolescencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Descanso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: adolescente', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: niño pequeño', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: preescolar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: segunda infancia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: seguridad física del adolescente', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: seguridad física del lactante y del niño pequeño', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: seguridad física en la primera y segunda infancia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Desempeño del rol de padres: seguridad psicosocial', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Deseo de vivir', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Detección del riesgo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Dolor: efectos nocivos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Dolor: respuesta psicológica adversa', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Efectividad de la bomba cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Efectividad de detección precoz sanitaria en la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Efectividad del programa comunitario', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Elaboración de la información', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Eliminación intestinal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Eliminación urinaria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Energía psicomotora', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Entorno seguro de asistencia sanitaria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Envejecimiento físico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Equilibrio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Equilibrio electrolítico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Equilibrio electrolítico y ácido-base', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Equilibrio emocional', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Equilibrio en el estilo de vida', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Equilibrio hídrico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Esperanza', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Establecimiento de la alimentación con biberón: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Establecimiento de la alimentación con taza: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Establecimiento de la lactancia materna: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Establecimiento de la lactancia materna: madre', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado cardiopulmonar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado circulatorio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de comodidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de comodidad: entorno', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de comodidad: física', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de comodidad: psicoespiritual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de comodidad: sociocultural', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de deglución', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de deglución: fase esofágica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de deglución: fase faríngea', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de deglución: fase oral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de inmunización de la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de salud de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de salud del estudiante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado de salud personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado fetal: durante el parto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado fetal: prenatal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado inmune', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado materno: durante el parto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado materno: preparto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado materno: puerperio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico: autónomo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico: consciencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico: control motor central', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico: función sensitiva/motora de pares craneales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico: función sensitiva/motora medular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado neurológico: periférico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado nutricional', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado nutricional: determinaciones bioquímicas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado nutricional: energía', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado nutricional: ingestión alimentaria y de líquidos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado nutricional: ingestión de nutrientes', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado nutricional del lactante', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado respiratorio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado respiratorio: intercambio gaseoso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado respiratorio: permeabilidad de las vías respiratorias', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Estado respiratorio: ventilación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Factores estresantes del cuidado familiar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Fatiga: efectos nocivos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Forma física', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Fugas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función esquelética', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función gastrointestinal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función hepática', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función metabólica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función renal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función sensitiva: auditiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función sensitiva: gusto y olfato', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función sensitiva: propioceptiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función sensitiva: táctil', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Función sensitiva: visión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Funcionamiento de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Funcionamiento de la familia: cuidado en la demencia ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Funcionamiento sexual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Gestión del tiempo personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Gravedad de la convulsión ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Habilidades de interacción social', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Hidratación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Identidad personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Identidad sexual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Imagen corporal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Implicación social', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Integridad de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Integridad del acceso para hemodiálisis', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Integridad tisular: piel y membranas mucosas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Lactancia materna: destete', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Lazos afectivos padres-hijo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Maduración física: femenina', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Maduración física: masculina', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Mantenimiento de la lactancia materna', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Marcha', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Memoria', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Modificación psicosocial: cambio de vida', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Motivación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movilidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: cadera', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: codo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: columna vertebral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: cuello', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: dedos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: hombro', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: muñeca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: pasivo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: rodilla', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento articular: tobillo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Movimiento coordinado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Muerte confortable', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Muerte digna', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Naúseas y vómitos: efectos nocivos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de agitación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de ansiedad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de ansiedad social', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de autocuidado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de delirio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de demencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de depresión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de estrés', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de fatiga', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de glucemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de hiperactividad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de malestar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de miedo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de miedo: infantil', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de pánico ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel de violencia social', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Nivel del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Normalización de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Normalización de la familia: demencia ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Normalización de la familia: trastorno del espectro autista ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Orientación cognitiva', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Orientación sobre la salud', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación de la familia en la asistencia sanitaria profesional', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación en actividades de ocio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación en el ejercicio', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación en juegos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación en la rehabilitación cardíaca ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación en la rehabilitación musculoesquelética ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Participación en las decisiones sobre la salud', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Pensamiento abstracto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular: cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular: celular', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular: cerebral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular: órganos abdominales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular: periférica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Perfusión tisular: pulmonar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Peso: masa corporal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Posición corporal: autoiniciada', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Preparación antes del procedimiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Preparación del cuidador familiar domiciliario', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Preparación para el alta: vida independiente', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Preparación para el alta: vivir con apoyo', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Preparación para un desastre en la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Protección del abuso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Quimioterapia: efectos físicos adversos ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Reacción transfusional sanguínea', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Realización de la alimentación con biberón', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Realización de la alimentación con taza', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Realización de transferencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación de las quemaduras', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación del acoso infantil ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación posterior al procedimiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación quirúrgica: convalecencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación quirúrgica: postoperatorio inmediato', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación tras abandono', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación tras el abuso', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación tras el abuso: económico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación tras el abuso: emocional', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación tras el abuso: físico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Recuperación tras el abuso: sexual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Relación entre el cuidador principal y el paciente', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Rendimiento de los mecanismos corporales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Rendimiento del cuidador principal: cuidados directos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Rendimiento del cuidador principal: cuidados indirectos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resiliencia de la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resiliencia familiar', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resiliencia personal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resistencia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resistencia del papel del cuidador', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resolución de la aflicción', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Resolución de la culpa', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta a la aflicción de la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta a la medicación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta alérgica: localizada', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta alérgica: sistémica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta ante un desastre en la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta de hipersensibilidad inmunológica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Respuesta de la ventilación mecánica: adulto', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Riesgo de tendencia a las fugas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Salud emocional del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Salud espiritual', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Salud física del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Salud oral', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: acceso a los recursos asistenciales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: asistencia funcional', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: aspectos técnicos del cuidado', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: comunicación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: continuidad de los cuidados', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: control de los síntomas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: cuidado físico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: cuidado psicológico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: cuidados', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: cumplimiento de las necesidades culturales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: enseñanza', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: entorno físico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: gestión de casos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: manejo del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: protección de sus derechos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Satisfacción del paciente/usuario: seguridad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la acidosis metabólica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la acidosis respiratoria aguda', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la alcalosis metabólica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la alcalosis respiratoria aguda', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la enfermedad arterial periférica', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipercalcemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipercloremia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hiperfosfatemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hiperglucemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipermagnesemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipernatremia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hiperpotasemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipocalcemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipocloremia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipofosfatemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipoglucemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipomagnesemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hiponatremia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipopotasemia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la hipotensión', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la infección', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la infección: recién nacido', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la lesión física', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la pérdida de sangre', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la retirada de sustancias', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la sobrecarga de líquidos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de la soledad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de las náuseas y los vómitos', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de los síntomas', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de los síntomas de la perimenopausia', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad de los síntomas del síndrome premenstrual (SPM)', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del linfedema ', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del ojo seco', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del shock: anafiláctico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del shock: cardiogénico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del shock: hipovolémico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del shock: neurogénico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del shock: séptico', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Severidad del sufrimiento', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Signos vitales', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Soporte social', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Sueño', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Termorregulación', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Termorregulación: recién nacido', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Tolerancia de la actividad', '1', FALSE);
insert  into  estandares.nanda_noc(nombre, version, deleted) values ('Toma de decisiones', '1', FALSE);
