from .dominios import *
from .clases import *
from .escalas import *
from .tipo_escala import *
from .noc import  *
from .indicadores import *
from .nic import *
from .actividades import *
from .diagnosticos import *
