DROP TABLE IF EXISTS estandares.nanda_noc CASCADE;
CREATE TABLE IF NOT EXISTS estandares.nanda_noc ( 
    id SERIAL PRIMARY KEY, 
    codigo TEXT NOT NULL, 
    nombre TEXT NOT NULL, 
    version TEXT NOT NULL, 
    deleted BOOLEAN DEFAULT FALSE 
);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1300', 'Aceptación: estado de la salud', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('2302', 'Aclaración de toxinas sistémicas: diálisis', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1308', 'Adaptación a la discapacidad física', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1311', 'Adaptación al traslado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2200', 'Adaptación del cuidador principal al ingreso del paciente en un centro sanitario', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1301', 'Adaptación del niño a la hospitalización', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0117', 'Adaptación del prematuro', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0118', 'Adaptación del recién nacido', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2600', 'Afrontamiento de los problemas de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1302', 'Afrontamiento de problemas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2014', 'Alfabetización económica ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2203', 'Alteración del estilo de vida del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1910', 'Ambiente seguro del hogar ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0200', 'Ambular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0201', 'Ambular: silla de ruedas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1014', 'Apetito', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2609', 'Apoyo familiar durante el tratamiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0918', 'Atención al lado afectado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('3123', 'Autocontrol: accidente cerebrovascular ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3120', 'Autocontol: alergia conocida ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3116', 'Autocontrol: anemia crónica ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3105', 'Autocontrol: arritmia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3112', 'Autocontrol: artritis ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0704', 'Autocontrol: asma', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3114', 'Autocontro: cáncer ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1619', 'Autocontrol: diabetes', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3100', 'Autocontrol: enfermedad aguda', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3104', 'Autocontrol: enfermedad arterial coronaria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3111', 'Autocontrol: enfermedad arterial periférica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1617', 'Autocontrol: enfermedad cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3115', 'Autocontrol: enfermedad celiaca (celiaquía) ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3102', 'Autocontrol: enfermedad crónica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3119', 'Autocontrol: enfermedad inflamatoria intestinal ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3103', 'Autocontrol: enfermedad pulmonar obstructiva crónica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3108', 'Autocontrol: enfermedad renal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1631', 'Autocontrol: esclerosis múltiple', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3124', 'Autocontrol: herida', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3107', 'Autocontrol: hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3118', 'Autocontrol: infección ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3106', 'Autocontrol: insuficiencia cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3121', 'Autocontrol: linfedema ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3122', ' Autocontrol: neumonía ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3110', 'Autocontrol: osteoporosis', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3113', 'Autocontrol: trastorno del espectro autista ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3109', 'Autocontrol: trastorno lipídico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3101', 'Autocontrol: tratamiento anticoagulante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3117', 'Autocontrol: virus de la inmunodeficiencia humana (VIH) ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1401', 'Autocontrol de la agresión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1402', 'Autocontrol de la ansiedad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1400', 'Autocontrol de la conducta abusiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1409', 'Autocontrol de la depresión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1410', 'Autocontrol de la ira', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1406', 'Autocontrol de la mutilación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1620', 'Autocontrol de las convulsiones', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1405', 'Autocontrol de los impulsos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1408', 'Autocontrol del impulso suicida', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1404', 'Autocontrol del miedo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1412', 'Autocontrol del pánico ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1403', 'Autocontrol del pensamiento distorsionado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1411', 'Autocontrol del trastorno de la alimentación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1615', 'Autocuidado de la ostomía', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0300', 'Autocuidados: actividades de la vida diaria (AVD)', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0306', 'Autocuidados: actividades instrumentales de la vida diaria (AIVD)', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0301', 'Autocuidados: baño', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0303', 'Autocuidados: comer', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0305', 'Autocuidados: higiene', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0308', 'Autocuidados: higiene oral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0307', 'Autocuidados: medicación no parenteral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0309', 'Autocuidados: medicación parenteral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0310', 'Autocuidados: uso del inodoro', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0302', 'Autocuidados: vestir', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1205', 'Autoestima', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1639', 'Autogestión de las actividades instrumentales de la vida diaria (AIVD) ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1613', 'Autogestión de los cuidados', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1614', 'Autonomía personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2508', 'Bienestar del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2002', 'Bienestar personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1912', 'Caídas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2000', 'Calidad de vida', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2513', 'Cese de la desatención', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2500', 'Cese del abuso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2601', 'Clima social de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0409', 'Coagulación sanguínea', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0900', 'Cognición', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2700', 'Competencia social', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('2015', 'Comportamiento de alfabetización en salud ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1638', 'Compromiso del paciente ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0902', 'Comunicación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0903', 'Comunicación: expresiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0904', 'Comunicación: receptiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0905', 'Concentración', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1215', 'Conciencia de uno mismo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1629', 'Conducta de abandono del consumo de alcohol', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1630', 'Conducta de abandono del consumo de drogas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1625', 'Conducta de abandono del consumo de tabaco', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1600', 'Conducta de adhesión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1621', 'Conducta de adhesión: dieta saludable', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1626', 'Conducta de aumento de peso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1603', 'Conducta de búsqueda de la salud', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1610', 'Conducta de compensación auditiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1611', 'Conducta de compensación visual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1601', 'Conducta de cumplimiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1632', 'Conducta de cumplimiento: actividad prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1622', 'Conducta de cumplimiento: dieta prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1623', 'Conducta de cumplimiento: medicación prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1602', 'Conducta de fomento de la salud', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1624', 'Conducta de la salud maternal en el postparto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1628', 'Conducta de mantenimiento del peso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1627', 'Conducta de pérdida de peso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1909', 'Conducta de prevención de caídas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1634', 'Conducta personal de detección precoz de enfermedades', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1607', 'Conducta sanitaria prenatal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1911', 'Conductas de seguridad personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1900', 'Conductas de vacunación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1811', 'Conocimiento: actividad prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1846', 'Conocimiento: alimentación con biberón', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1850', 'Conocimiento: alimentación con taza', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1805', 'Conocimiento: conducta sanitaria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1804', 'Conocimiento: conservación de la energía', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1820', 'Conocimiento: control de la diabetes', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1830', 'Conocimiento: control de la enfermedad cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1837', 'Conocimiento: control de la hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1842', 'Conocimiento: control de la infección', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1812', 'Conocimiento: control del consumo de sustancias', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1826', 'Conocimiento: cuidado de los hijos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1829', 'Conocimiento: cuidados de la ostomía', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1819', 'Conocimiento: cuidados del lactante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1840', 'Conocimiento: cuidados del recién nacido pretérmino', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1802', 'Conocimiento: dieta prescrita', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1854', 'Conocimiento: dieta saludable', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1855', 'Conocimiento: estilo de vida saludable', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1816', 'Conocimiento: fomento de la fertilidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1815', 'Conocimiento: funcionamiento sexual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1839', 'Conocimiento: funcionamiento sexual durante el embarazo y el postparto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1810', 'Conocimiento: gestación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1866', 'Conocimiento: gestión del tiempo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1800', 'Conocimiento: lactancia materna', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3209', 'Conocimiento: manejo de heridas ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3200', 'Conocimiento: manejo de la alergia ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3204', 'Conocimiento: manejo de la anemia crónica ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1852', 'Conocimiento: manejo de la arritmia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1831', 'Conocimiento: manejo de la artritis', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1851', 'Conocimiento: manejo de la demencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1836', 'Conocimiento: manejo de la depresión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1844', 'Conocimiento: manejo de la enfermedad aguda', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1849', 'Conocimiento: manejo de la enfermedad arterial coronaria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1860', 'Conocimiento: manejo de la enfermedad arterial periférica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3203', 'Conocimiento: manejo de la enfermedad celiaca ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1863', 'Conocimiento: manejo de la enfermedad cerebrovascular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1847', 'Conocimiento: manejo de la enfermedad crónica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1856', 'Conocimiento: manejo de la enfermedad inflamatoria intestinal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1848', 'Conocimiento: manejo de la enfermedad pulmonar obstructiva crónica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1857', 'Conocimiento: manejo de la enfermedad renal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3205', 'Conocimiento: manejo de la epilepsia ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1838', 'Conocimiento: manejo de la esclerosis múltiple', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1835', 'Conocimiento: manejo de la insuficiencia cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1861', 'Conocimiento: manejo de la neumonía', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1859', 'Conocimiento: manejo de la osteoporosis', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1832', 'Conocimiento: manejo del asma', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1833', 'Conocimiento: manejo del cáncer', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1843', 'Conocimiento: manejo del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1862', 'Conocimiento: manejo del estrés', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3207', 'Conocimiento: manejo del linfedema ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1841', 'Conocimiento: manejo del peso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1853', 'Conocimiento: manejo del trastorno de la alimentación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3201', 'Conocimiento: manejo del trastorno del espectro autista ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1858', 'Conocimiento: manejo del trastorno lipídico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1845', 'Conocimiento: manejo del tratamiento anticoagulante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3206', 'Conocimiento: manejo del virus de la inmunodeficiencia humana ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1827', 'Conocimiento: mecanismos corporales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1808', 'Conocimiento: medicación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1817', 'Conocimiento: parto y alumbramiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1828', 'Conocimiento: prevención de caídas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1821', 'Conocimiento: prevención del embarazo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1814', 'Conocimiento: procedimiento terapéutico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1867', 'Conocimiento: procedimientos diagnósticos y terapéuticos ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1803', 'Conocimiento: proceso de la enfermedad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1806', 'Conocimiento: recursos sanitarios', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1864', 'Conocimiento: reducción de la amenaza de accidente cerebrovascular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1834', 'Conocimiento: reducción de la amenaza del cáncer', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1865', 'Conocimiento: reducción de la amenaza de trombo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1813', 'Conocimiento: régimen terapéutico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('3202', 'Conocimiento: rehabilitación cardiaca ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3208', 'Conocimiento: rehabilitación musculoesquelética ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1818', 'Conocimiento: salud materna en el puerperio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1822', 'Conocimiento: salud materna en la preconcepción', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1801', 'Conocimiento: seguridad física infantil', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1809', 'Conocimiento: seguridad personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1407', 'Consecuencias de la adicción a sustancias psicoactivas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0204', 'Consecuencias de la inmovilidad: fisiológicas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0205', 'Consecuencias de la inmovilidad: psicocognitivas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0002', 'Conservación de la energía', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0500', 'Continencia intestinal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0502', 'Continencia urinaria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1618', 'Control de náuseas y vómitos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1608', 'Control de síntomas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1605', 'Control del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1902', 'Control del riesgo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1931', 'Control del riesgo: accidente cerebrovascular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1936', 'Control del riesgo: acoso infantil ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1940', 'Control del riesgo: alergias infantiles ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1935', 'Control del riesgo: aspiración ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1939', 'Control del riesgo: caídas ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1917', 'Control del riesgo: cáncer', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1903', 'Control del riesgo: consumo de alcohol', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1904', 'Control del riesgo: consumo de drogas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1906', 'Control del riesgo: consumo de tabaco', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1937', 'Control del riesgo: deshidratación ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1915', 'Control del riesgo: deterioro auditivo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1916', 'Control del riesgo: deterioro visual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1907', 'Control del riesgo: embarazo no deseado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1914', 'Control del riesgo: enfermedad cardiovascular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1905', 'Control del riesgo: enfermedades de transmisión sexual (ETS)', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1925', 'Control del riesgo: exposición al sol', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1942', 'Control del riesgo: herida por presión (úlcera por presión) ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1928', 'Control del riesgo: hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1922', 'Control del riesgo: hipertermia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1933', 'Control del riesgo: hipotensión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1923', 'Control del riesgo: hipotermia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1941', 'Control del riesgo: obesidad ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1927', 'Control del riesgo: ojo seco', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1930', 'Control del riesgo: osteoporosis', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1938', 'Control del riesgo: peligros medioambientales ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1924', 'Control del riesgo: proceso infeccioso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1929', 'Control del riesgo: trastorno lipídico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1932', 'Control del riesgo: trombos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2612', 'Control del riesgo familiar: acoso ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2610', 'Control del riesgo familiar: obesidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2811', 'Control del riesgo social: acoso infantil ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2801', 'Control del riesgo social: enfermedad crónica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2802', 'Control del riesgo social: enfermedad transmisible', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2803', 'Control del riesgo social: exposición al plomo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2809', 'Control del riesgo social: obesidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2812', 'Control del riesgo social: peligros medioambientales ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2813', 'Control del riesgo social: suicidio ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2810', 'Control del riesgo social: tradiciones culturales no saludables', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2805', 'Control del riesgo social: violencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0110', 'Crecimiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1700', 'Creencias sobre la salud', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1701', 'Creencias sobre la salud: capacidad percibida para actuar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1704', 'Creencias sobre la salud: percepción de amenaza', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1702', 'Creencias sobre la salud: percepción de control', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1703', 'Creencias sobre la salud: percepción de recursos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1102', 'Curación de la herida: por primera intención', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1103', 'Curación de la herida: por segunda intención', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1106', 'Curación de las quemaduras', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1104', 'Curación ósea', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1926', 'Deambulación segura', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0122', 'Desarrollo: adulto de mediana edad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0123', 'Desarrollo: adulto joven', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0121', 'Desarrollo: adulto mayor', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0120', 'Desarrollo infantil: 1 mes', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0100', 'Desarrollo infantil: 2 meses', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0101', 'Desarrollo infantil: 4 meses', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0102', 'Desarrollo infantil: 6 meses', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('0103', 'Desarrollo infantil: 12 meses', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0104', 'Desarrollo infantil: 2 años', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0105', 'Desarrollo infantil: 3 años', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0106', 'Desarrollo infantil: 4 años', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0107', 'Desarrollo infantil: 5 años', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0108', 'Desarrollo infantil: segunda infancia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0109', 'Desarrollo infantil: adolescencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0003', 'Descanso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1501', 'Desempeño del rol', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2211', 'Desempeño del rol de padres', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2903', 'Desempeño del rol de padres: adolescente', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2904', 'Desempeño del rol de padres: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2907', 'Desempeño del rol de padres: niño pequeño', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2906', 'Desempeño del rol de padres: preescolar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2905', 'Desempeño del rol de padres: segunda infancia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2902', 'Desempeño del rol de padres: seguridad física del adolescente', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2900', 'Desempeño del rol de padres: seguridad física del lactante y del niño pequeño', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2901', 'Desempeño del rol de padres: seguridad física en la primera y segunda infancia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1901', 'Desempeño del rol de padres: seguridad psicosocial', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1206', 'Deseo de vivir', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1908', 'Detección del riesgo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2101', 'Dolor: efectos nocivos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1306', 'Dolor: respuesta psicológica adversa', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0400', 'Efectividad de la bomba cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2807', 'Efectividad de detección precoz sanitaria en la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2808', 'Efectividad del programa comunitario', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0907', 'Elaboración de la información', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0501', 'Eliminación intestinal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0503', 'Eliminación urinaria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0006', 'Energía psicomotora', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1934', 'Entorno seguro de asistencia sanitaria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0113', 'Envejecimiento físico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('0202', 'Equilibrio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0606', 'Equilibrio electrolítico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0600', 'Equilibrio electrolítico y ácido-base', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1204', 'Equilibrio emocional', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2013', 'Equilibrio en el estilo de vida', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0601', 'Equilibrio hídrico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1201', 'Esperanza', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1016', 'Establecimiento de la alimentación con biberón: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1018', 'Establecimiento de la alimentación con taza: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1000', 'Establecimiento de la lactancia materna: lactante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1001', 'Establecimiento de la lactancia materna: madre', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0414', 'Estado cardiopulmonar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0401', 'Estado circulatorio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2008', 'Estado de comodidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2009', 'Estado de comodidad: entorno', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2010', 'Estado de comodidad: física', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2011', 'Estado de comodidad: psicoespiritual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2012', 'Estado de comodidad: sociocultural', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1010', 'Estado de deglución', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1011', 'Estado de deglución: fase esofágica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1013', 'Estado de deglución: fase faríngea', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1012', 'Estado de deglución: fase oral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2800', 'Estado de inmunización de la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2606', 'Estado de salud de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2005', 'Estado de salud del estudiante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2006', 'Estado de salud personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0112', 'Estado fetal: durante el parto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0111', 'Estado fetal: prenatal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0702', 'Estado inmune', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2510', 'Estado materno: durante el parto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2509', 'Estado materno: preparto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2511', 'Estado materno: puerperio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0909', 'Estado neurológico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0910', 'Estado neurológico: autónomo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('0912', 'Estado neurológico: consciencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0911', 'Estado neurológico: control motor central', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0913', 'Estado neurológico: función sensitiva/motora de pares craneales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0914', 'Estado neurológico: función sensitiva/motora medular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0917', 'Estado neurológico: periférico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1004', 'Estado nutricional', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1005', 'Estado nutricional: determinaciones bioquímicas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1007', 'Estado nutricional: energía', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1008', 'Estado nutricional: ingestión alimentaria y de líquidos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1009', 'Estado nutricional: ingestión de nutrientes', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1020', 'Estado nutricional del lactante', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0415', 'Estado respiratorio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0402', 'Estado respiratorio: intercambio gaseoso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0410', 'Estado respiratorio: permeabilidad de las vías respiratorias', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0403', 'Estado respiratorio: ventilación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2208', 'Factores estresantes del cuidado familiar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0008', 'Fatiga: efectos nocivos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2004', 'Forma física', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1919', 'Fugas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0211', 'Función esquelética', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1015', 'Función gastrointestinal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0803', 'Función hepática', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0804', 'Función metabólica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0504', 'Función renal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2401', 'Función sensitiva: auditiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2403', 'Función sensitiva: gusto y olfato', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2402', 'Función sensitiva: propioceptiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2400', 'Función sensitiva: táctil', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2404', 'Función sensitiva: visión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2602', 'Funcionamiento de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2212', 'Funcionamiento de la familia: cuidado en la demencia ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0119', 'Funcionamiento sexual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1635', 'Gestión del tiempo personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2118', 'Gravedad de la convulsión ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1502', 'Habilidades de interacción social', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0602', 'Hidratación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1202', 'Identidad personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1207', 'Identidad sexual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1200', 'Imagen corporal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1503', 'Implicación social', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2603', 'Integridad de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1105', 'Integridad del acceso para hemodiálisis', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1101', 'Integridad tisular: piel y membranas mucosas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1003', 'Lactancia materna: destete', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1500', 'Lazos afectivos padres-hijo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0114', 'Maduración física: femenina', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0115', 'Maduración física: masculina', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1002', 'Mantenimiento de la lactancia materna', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0222', 'Marcha', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0908', 'Memoria', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1305', 'Modificación psicosocial: cambio de vida', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1209', 'Motivación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0208', 'Movilidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0206', 'Movimiento articular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0216', 'Movimiento articular: cadera', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0214', 'Movimiento articular: codo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0220', 'Movimiento articular: columna vertebral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0218', 'Movimiento articular: cuello', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0215', 'Movimiento articular: dedos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0219', 'Movimiento articular: hombro', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0221', 'Movimiento articular: muñeca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0207', 'Movimiento articular: pasivo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0217', 'Movimiento articular: rodilla', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0213', 'Movimiento articular: tobillo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0212', 'Movimiento coordinado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2007', 'Muerte confortable', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1307', 'Muerte digna', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2106', 'Naúseas y vómitos: efectos nocivos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('1214', 'Nivel de agitación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1211', 'Nivel de ansiedad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1216', 'Nivel de ansiedad social', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0313', 'Nivel de autocuidado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0916', 'Nivel de delirio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0920', 'Nivel de demencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1208', 'Nivel de depresión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1212', 'Nivel de estrés', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0007', 'Nivel de fatiga', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2300', 'Nivel de glucemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0915', 'Nivel de hiperactividad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2109', 'Nivel de malestar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1210', 'Nivel de miedo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1213', 'Nivel de miedo: infantil', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1217', 'Nivel de pánico ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2702', 'Nivel de violencia social', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2102', 'Nivel del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2604', 'Normalización de la familia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2611', 'Normalización de la familia: demencia ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2613', 'Normalización de la familia: trastorno del espectro autista ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0901', 'Orientación cognitiva', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1705', 'Orientación sobre la salud', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2605', 'Participación de la familia en la asistencia sanitaria profesional', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1604', 'Participación en actividades de ocio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1633', 'Participación en el ejercicio', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0116', 'Participación en juegos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1636', 'Participación en la rehabilitación cardíaca ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1637', 'Participación en la rehabilitación musculoesquelética ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1606', 'Participación en las decisiones sobre la salud', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0919', 'Pensamiento abstracto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0422', 'Perfusión tisular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0405', 'Perfusión tisular: cardíaca', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0416', 'Perfusión tisular: celular', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0406', 'Perfusión tisular: cerebral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('0404', 'Perfusión tisular: órganos abdominales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0407', 'Perfusión tisular: periférica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0408', 'Perfusión tisular: pulmonar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1006', 'Peso: masa corporal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0203', 'Posición corporal: autoiniciada', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1921', 'Preparación antes del procedimiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2202', 'Preparación del cuidador familiar domiciliario', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0311', 'Preparación para el alta: vida independiente', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0312', 'Preparación para el alta: vivir con apoyo', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2804', 'Preparación para un desastre en la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2501', 'Protección del abuso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2116', 'Quimioterapia: efectos físicos adversos ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0700', 'Reacción transfusional sanguínea', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1017', 'Realización de la alimentación con biberón', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1019', 'Realización de la alimentación con taza', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0210', 'Realización de transferencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1107', 'Recuperación de las quemaduras', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1312', 'Recuperación del acoso infantil ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2303', 'Recuperación posterior al procedimiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2304', 'Recuperación quirúrgica: convalecencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2305', 'Recuperación quirúrgica: postoperatorio inmediato', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2512', 'Recuperación tras abandono', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2514', 'Recuperación tras el abuso', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2503', 'Recuperación tras el abuso: económico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2502', 'Recuperación tras el abuso: emocional', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2504', 'Recuperación tras el abuso: físico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2505', 'Recuperación tras el abuso: sexual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2204', 'Relación entre el cuidador principal y el paciente', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1616', 'Rendimiento de los mecanismos corporales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2205', 'Rendimiento del cuidador principal: cuidados directos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2206', 'Rendimiento del cuidador principal: cuidados indirectos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2704', 'Resiliencia de la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2608', 'Resiliencia familiar', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1309', 'Resiliencia personal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('0001', 'Resistencia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2210', 'Resistencia del papel del cuidador', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1304', 'Resolución de la aflicción', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1310', 'Resolución de la culpa', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2703', 'Respuesta a la aflicción de la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2301', 'Respuesta a la medicación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0705', 'Respuesta alérgica: localizada', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0706', 'Respuesta alérgica: sistémica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2806', 'Respuesta ante un desastre en la comunidad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0707', 'Respuesta de hipersensibilidad inmunológica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0411', 'Respuesta de la ventilación mecánica: adulto', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1920', 'Riesgo de tendencia a las fugas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2506', 'Salud emocional del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2001', 'Salud espiritual', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2507', 'Salud física del cuidador principal', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1100', 'Salud oral', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3014', 'Satisfacción del paciente/usuario', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3000', 'Satisfacción del paciente/usuario: acceso a los recursos asistenciales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3005', 'Satisfacción del paciente/usuario: asistencia funcional', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3013', 'Satisfacción del paciente/usuario: aspectos técnicos del cuidado', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3002', 'Satisfacción del paciente/usuario: comunicación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3003', 'Satisfacción del paciente/usuario: continuidad de los cuidados', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3011', 'Satisfacción del paciente/usuario: control de los síntomas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3006', 'Satisfacción del paciente/usuario: cuidado físico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3009', 'Satisfacción del paciente/usuario: cuidado psicológico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3001', 'Satisfacción del paciente/usuario: cuidados', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3004', 'Satisfacción del paciente/usuario: cumplimiento de las necesidades culturales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3012', 'Satisfacción del paciente/usuario: enseñanza', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3007', 'Satisfacción del paciente/usuario: entorno físico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3015', 'Satisfacción del paciente/usuario: gestión de casos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3016', 'Satisfacción del paciente/usuario: manejo del dolor', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3008', 'Satisfacción del paciente/usuario: protección de sus derechos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 3010', 'Satisfacción del paciente/usuario: seguridad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0619', 'Severidad de la acidosis metabólica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0604', 'Severidad de la acidosis respiratoria aguda', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0620', 'Severidad de la alcalosis metabólica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0605', 'Severidad de la alcalosis respiratoria aguda', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2115', 'Severidad de la enfermedad arterial periférica', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0607', 'Severidad de la hipercalcemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0608', 'Severidad de la hipercloremia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0612', 'Severidad de la hiperfosfatemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2111', 'Severidad de la hiperglucemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0610', 'Severidad de la hipermagnesemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0611', 'Severidad de la hipernatremia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0609', 'Severidad de la hiperpotasemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2112', 'Severidad de la hipertensión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0613', 'Severidad de la hipocalcemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0614', 'Severidad de la hipocloremia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0618', 'Severidad de la hipofosfatemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2113', 'Severidad de la hipoglucemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0616', 'Severidad de la hipomagnesemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0617', 'Severidad de la hiponatremia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0615', 'Severidad de la hipopotasemia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2114', 'Severidad de la hipotensión', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0703', 'Severidad de la infección', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0708', 'Severidad de la infección: recién nacido', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1913', 'Severidad de la lesión física', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0413', 'Severidad de la pérdida de sangre', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2108', 'Severidad de la retirada de sustancias', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0603', 'Severidad de la sobrecarga de líquidos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1203', 'Severidad de la soledad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2107', 'Severidad de las náuseas y los vómitos', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2103', 'Severidad de los síntomas', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2104', 'Severidad de los síntomas de la perimenopausia', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2105', 'Severidad de los síntomas del síndrome premenstrual (SPM)', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2117', 'Severidad del linfedema ', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2110', 'Severidad del ojo seco', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values ('0417', 'Severidad del shock: anafiláctico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0418', 'Severidad del shock: cardiogénico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0419', 'Severidad del shock: hipovolémico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0420', 'Severidad del shock: neurogénico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0421', 'Severidad del shock: séptico', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 2003', 'Severidad del sufrimiento', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0802', 'Signos vitales', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 1504', 'Soporte social', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0004', 'Sueño', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0800', 'Termorregulación', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0801', 'Termorregulación: recién nacido', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0005', 'Tolerancia de la actividad', '1', FALSE);
insert  into  estandares.nanda_noc(codigo, nombre, version, deleted) values (' 0906', 'Toma de decisiones', '1', FALSE);
