CREATE TABLE IF NOT EXISTS estandares.nanda_diagnostico ( 
    id SERIAL PRIMARY KEY, 
    clase_fk INTEGER, 
    codigo TEXT NOT NULL, 
    nombre TEXT NOT NULL, 
    version TEXT NOT NULL, 
    deleted BOOLEAN DEFAULT FALSE, 
    CONSTRAINT nanda_clase_fk FOREIGN KEY (clase_fk) REFERENCES estandares.nanda_clase(id) 
);
CREATE TABLE IF NOT EXISTS estandares.nanda_nic_nanda_diagnostico ( 
    nanda_fk INTEGER, 
    nic_fk   INTEGER, 
    CONSTRAINT nanda_rel FOREIGN KEY (nanda_fk) REFERENCES estandares.nanda_diagnostico(id), 
    CONSTRAINT nic_rel FOREIGN KEY (nic_fk) REFERENCES estandares.nanda_nic(id) 
);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (1, 1, '00262', 'Disposición para mejorar la alfabetización en salud  ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (2, 1, '00168', 'Estilo de vida sedentario ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (3, 1, '00097', 'Disminución de la implicación en actividades recreativa', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (3, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (4, 1, '00290', 'Riesgo de intento de fuga', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (5, 1, '00307', 'Disposición para mejorar la realización de ejercicio ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (6, 2, '00188', 'Tendencia a adoptar conductas de riesgo para la salud ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (6, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (7, 2, '00276', 'Autogestión ineficaz de la salud', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (7, 62);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (7, 119);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (7, 124);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (8, 2, '00293', 'Disposición para mejorar la autogestión de la salud', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (9, 2, '00294', 'Autogestión ineficaz de la salud familiar ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (10, 2, '00292', 'Conductas ineficaces para el mantenimiento de la salud ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (10, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (11, 2, '00300', 'Conductas ineficaces para el mantenimiento del hogar ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (12, 2, '00308', 'Riesgo de conductas ineficaces para el mantenimiento del hogar', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (13, 2, '00309', 'Disposición para mejorar las conductas de mantenimiento del hogar ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (14, 2, '00043', 'Protección ineficaz ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (14, 55);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (15, 2, '00215', 'Salud deficiente de la comunidad ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (16, 2, '00231', 'Riesgo de síndrome de fragilidad del anciano ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (17, 2, '00257', 'Síndrome de fragilidad del anciano ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (18, 3, '00103', 'Deterioro de la deglución', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (19, 3, '00002', 'Desequilibrio nutricional:ingesta inferior a las necesidades corporales ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (20, 3, '00163', 'Disposición para mejorar la nutrición ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (21, 3, '00271', 'Dinámica de alimentación ineficaz del lactante', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (22, 3, '00269', 'Dinámica de comidas ineficaz del adolescente', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (23, 3, '00270', 'Dinámica de comidas ineficaz del niño', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (24, 3, '00104', 'Lactancia materna ineficaz ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (25, 3, '00105', 'Interrupción de la lactancia materna', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (26, 3, '00106', 'Disposición para mejorar la lactancia materna  ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (27, 3, '00295', 'Respuesta ineficaz de succión-deglución infantil ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (28, 3, '00216', 'Producción insuficiente de lecha materna', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (29, 3, '00234', 'Riesgo de sobrepeso', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (30, 3, '00233', 'Sobrepeso', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (31, 3, '00232', 'Obesidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (32, 6, '00178', 'Riesgo de deterioro de la función hepática ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (33, 6, '00179', 'Riesgo de nivel de glucemia inestable', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (34, 6, '00230', 'Riesgo de hiperbilirrubinemia neonatal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (35, 6, '00194', 'Hiperbilirrubinemia neonatal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (36, 6, '00296', 'Riesgo de síndrome metabólico ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (37, 7, '00025', 'Riesgo de desequilibrio de volumen de líquidos ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (37, 55);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (38, 7, '00195', 'Riesgo de desequilibrio electrolítico ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (39, 7, '00028', 'Riesgo de déficit de volumen de líquidos', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (39, 55);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (40, 7, '00027', 'Déficit de volumen de líquidos ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (40, 55);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (40, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (41, 7, '00026', 'Exceso de volumen de líquidos ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (41, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (42, 8, '00016', 'Deterioro de la eliminación urinaria', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (42, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (43, 8, '00017', 'Incontinencia urinaria de esfuerzo', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (44, 8, '00022', 'Riesgo de incontinencia urinaria de urgencia ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (45, 8, '00019', 'Incontinencia urinaria de urgencia ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (46, 8, '00297', 'Incontinencia urinaria asociada a discapacidad ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (47, 8, '00023', 'Retención urinaria', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (47, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (48, 8, '00310', 'Incontinencia urinaria mixta', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (49, 8, '00322', 'Riesgo de retención urinaria ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (50, 9, '00013', 'Diarrea', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (50, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (51, 9, '00015', 'Riesgo de estreñimiento', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (52, 9, '00011', 'Estreñimiento ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (52, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (53, 9, '00236', 'Riesgo de estreñimiento funcional crónico ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (54, 9, '00235', 'Estreñimiento funcional crónico ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (55, 9, '00012', 'Estreñimiento subjetivo ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (56, 9, '00319', 'Continencia intestinal alterada', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (57, 9, '00197', 'Riesgo de motilidad gastrointestinal disfuncional', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (58, 9, '00196', 'Motilidad gastrointestinal disfuncional', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (59, 11, '00030', 'Deterioro del intercambio de gases', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (59, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (60, 12, '00095', 'Insomnio', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (60, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (61, 12, '00198', 'Trastorno del patrón de sueño', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (61, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (62, 12, '00096', 'Deprivación de sueño', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (62, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (63, 12, '00165', 'Disposición para mejorar el sueño', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (64, 13, '00088', 'Deterioro de la ambulación', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (64, 29);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (65, 13, '00238', 'Deterioro de la bipedestación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (66, 13, '00090', 'Deterioro de la habilidad para la traslación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (67, 13, '00091', 'Deterioro de la movilidad en la cama ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (68, 13, '00089', 'Deterioro de la movilidad en silla de ruedas ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (69, 13, '00085', 'Deterioro de la movilidad física ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (69, 29);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (70, 13, '00237', 'Deterioro de la sedestación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (71, 13, '00040', 'Riesgo de síndrome de desuso', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (71, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (71, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (72, 14, '00273', 'Desequilibrio del campo energético', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (73, 14, '00093', 'Fatiga ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (74, 14, '00154', 'Vagabundeo', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (75, 15, '00240', 'Riesgo de disminución del gasto cardíaco ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (76, 15, '00029', 'Disminución del gasto cardíaco', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (76, 55);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (76, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (77, 15, '00299', 'Riesgo de tolerancia disminuida a la actividad ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (78, 15, '00298', 'Tolerancia disminuida a la actividad ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (79, 15, '00032', 'Patrón respiratorio ineficaz ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (79, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (79, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (80, 15, '00200', 'Riesgo de disminución de la perfusión tisular cardíaca', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (81, 15, '00201', 'Riesgo de perfusión cerebral ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (82, 15, '00228', 'Riesgo de perfusión tisular periférica ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (83, 15, '00204', 'Perfusión tisular periférica ineficaz', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (83, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (84, 15, '00034', 'Respuesta ventilatoria disfuncional al destete ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (84, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (85, 15, '00267', 'Riesgo de tensión arterial inestable', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (86, 15, '00033', 'Deterioro de la ventilación espontánea ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (86, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (87, 15, '00311', 'Riesgo de deterioro de la función cardiovascular ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (88, 15, '00278', 'Autogestión ineficaz del linfedema ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (89, 15, '00281', 'Riesgo de autogestión ineficaz del linfedema ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (90, 15, '00291', 'Riesgo de trombosis ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (91, 15, '00318', 'Respuesta ventilatoria disfuncional al destete en el adulto ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (92, 16, '00102', 'Déficit de autocuidado en la alimentación', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (92, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (93, 16, '00108', 'Déficit de autocuidado en el baño ', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (93, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (94, 16, '00110', 'Déficit de autocuidado en el uso del inodoro', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (94, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (95, 16, '00109', 'Déficit de autocuidado en el vestido', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (95, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (96, 16, '00182', 'Disposición para mejorar el autocuidado ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (97, 16, '00193', 'Descuido personal ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (98, 17, '00123', 'Desatención unilateral ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (99, 20, '00173', 'Riesgo de confusión aguda ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (100, 20, '00128', 'Confusión aguda', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (100, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (100, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (101, 20, '00129', 'Confusión crónica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (102, 20, '00126', 'Conocimientos deficientes', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (102, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (102, 124);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (103, 20, '00161', 'Disposición para mejorar los conocimientos ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (104, 20, '00222', 'Control de impulsos ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (105, 20, '00251', 'Control emocional inestable', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (106, 20, '00131', 'Deterioro de la memoria', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (106, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (107, 20, '00279', 'Trastornos de los proceso de pensamiento  ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (108, 21, '00051', 'Deterioro de la comunicación verbal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (109, 21, '00157', 'Disposición para mejorar la comunicación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (110, 22, '00167', 'Disposición para mejorar el autoconcepto', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (111, 22, '00174', 'Riesgo de compromiso de la dignidad humana', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (112, 22, '00124', 'Desesperanza', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (112, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (113, 22, '00185', 'Disposición para mejorar la esperanza', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (114, 22, '00225', 'Riesgo de trastorno de la identidad personal ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (115, 22, '00121', 'Trastorno de la identidad personal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (116, 23, '00224', 'Riesgo de baja autoestima crónica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (117, 23, '00119', 'Baja autoestima crónica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (118, 23, '00153', 'Riesgo de baja autoestima situacional', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (119, 23, '00120', 'Baja autoestima situacional', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (120, 24, '00118', 'Trastorno de la imagen corporal', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (120, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (121, 25, '00062', 'Riesgo de cansancio del rol de cuidador', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (122, 25, '00061', 'Cansancio del rol de cuidador', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (123, 25, '00057', 'Riesgo de deterioro parental', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (123, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (124, 25, '00056', 'Deterioro parental', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (124, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (125, 25, '00164', 'Disposición para mejorar el rol parental', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (126, 26, '00060', 'Interrupción de los procesos familiares', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (127, 26, '00063', 'Procesos familiares disfuncionales', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (127, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (128, 26, '00159', 'Disposición para mejorar los procesos familiares', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (129, 26, '00058', 'Riesgo de deterioro de la vinculación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (130, 26, '00283', 'Síndrome de identidad familiar alterada ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (131, 26, '00284', 'Riesgo de síndrome de identidad familiar alterada ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (132, 27, '00064', 'Conflicto del rol parental', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (133, 27, '00055', 'Desempeño ineficaz del rol', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (134, 27, '00052', 'Deterioro de la interacción social', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (135, 27, '00229', 'Riesgo de relación ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (136, 27, '00223', 'Relación ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (137, 27, '00207', 'Disposición para mejorar la relación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (138, 29, '00059', 'Disfunción sexual', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (139, 29, '00065', 'Patrón sexual ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (140, 30, '00209', 'Riesgo de alteración de la díada materno/fetal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (141, 30, '00227', 'Riesgo de proceso de maternidad ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (142, 30, '00221', 'Proceso de maternidad ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (143, 30, '00208', 'Disposición para mejorar el proceso de maternidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (144, 31, '00149', 'Riesgo de síndrome de estrés del traslado', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (145, 31, '00114', 'Síndrome de estrés del traslado', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (146, 31, '00142', 'Síndrome del trauma postviolación', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (146, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (147, 31, '00145', 'Riesgo de síndrome postraumático', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (148, 31, '00141', 'Síndrome postraumático', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (148, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (149, 31, '00260', 'Riesgo de transición migratoria complicada', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (150, 32, '00137', 'Aflicción crónica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (151, 32, '00071', 'Afrontamiento defensivo', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (151, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (152, 32, '00069', 'Afrontamiento ineficaz', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (152, 1);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (152, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (153, 32, '00158', 'Disposición para mejorar el afrontamiento', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (154, 32, '00074', 'Afrontamiento familiar comprometido', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (155, 32, '00073', 'Afrontamiento familiar incapacitante', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (156, 32, '00075', 'Disposición para mejorar el afrontamiento familiar', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (157, 32, '00077', 'Afrontamiento ineficaz de la comunidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (158, 32, '00076', 'Disposición para mejorar el afrontamiento de la comunidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (159, 32, '00146', 'Ansiedad', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (159, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (160, 32, '00147', 'Ansiedad ante la muerte', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (160, 29);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (161, 32, '00302', ' Riesgo de duelo no adaptativo ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (162, 32, '00301', 'Duelo no adaptativo ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (163, 32, '00285', 'Disposición para mejorar el duelo', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (164, 32, '00177', 'Estrés por sobrecarga', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (164, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (165, 32, '00072', 'Negación ineficaz', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (165, 1);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (165, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (166, 32, '00226', 'Riesgo de planificación ineficaz de las actividades', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (167, 32, '00199', 'Planificación ineficaz de las actividades', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (168, 32, '00152', 'Riesgo de impotencia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (169, 32, '00125', 'Impotencia', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (169, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (170, 32, '00187', 'Disposición para mejorar el poder', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (171, 32, '00241', 'Deterioro de la regulación del estado de ánimo', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (172, 32, '00211', 'Riesgo de deterioro de la resiliencia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (173, 32, '00210', 'Deterioro de la resiliencia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (174, 32, '00212', 'Disposición para mejorar la resiliencia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (175, 32, '00148', 'Temor', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (176, 33, '00115', 'Riesgo de conducta desorganizada del lactante', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (177, 33, '00116', 'Conducta desorganizada del lactante', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (178, 33, '00117', 'Disposición para mejorar la conducta organizada del lactante', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (179, 33, '00010', 'Riesgo de disreflexia autonómica', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (179, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (180, 33, '00009', 'Disreflexia autonómica', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (180, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (181, 33, '00259', 'Riesgo de síndrome de abstinencia agudo', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (182, 33, '00258', 'Síndrome de abstinencia agudo', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (183, 33, '00264', 'Síndrome de abstinencia neonatal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (184, 35, '00068', 'Disposición para mejorar el bienestar espiritual', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (185, 36, '00083', 'Conflicto de decisiones', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (185, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (186, 36, '00170', 'Riesgo de deterioro de la religiosidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (187, 36, '00169', 'Deterioro de la religiosidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (188, 36, '00171', 'Disposición para mejorar la religiosidad', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (189, 36, '00067', 'Riesgo de sufrimiento espiritual', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (190, 36, '00066', 'Sufrimiento espiritual', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (191, 36, '00175', 'Sufrimiento moral', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (192, 36, '00184', 'Disposición para mejorar la toma de decisiones', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (193, 36, '00244', 'Riesgo de deterioro de la toma de decisiones independiente', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (194, 36, '00242', 'Deterioro de la toma de decisiones independiente', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (195, 36, '00243', 'Disposición para mejorar la toma de decisiones independiente', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (196, 37, '00004', 'Riesgo de infección', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (197, 37, '00266', 'Riesgo de infección de la herida quirúrgica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (198, 38, '00036', 'Riesgo de asfixia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (199, 38, '00039', 'Riesgo de aspiración', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (199, 119);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (200, 38, '00303', 'Riesgo de caída en el adulto', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (201, 38, '00306', 'Riesgo de caída en el niño ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (202, 38, '00048', 'Deterioro de la dentición', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (203, 38, '00086', 'Riesgo de disfunción neurovascular periférica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (204, 38, '00047', 'Riesgo de deterioro de la integridad cutánea', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (205, 38, '00046', 'Deterioro de la integridad cutánea', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (205, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (205, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (206, 38, '00247', 'Riesgo de deterioro de la mucosa oral', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (207, 38, '00045', 'Deterioro de la mucosa oral', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (208, 38, '00248', 'Riesgo de deterioro de la integración tisular', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (209, 38, '00044', 'Deterioro de la integridad tisular', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (209, 55);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (209, 62);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (209, 119);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (210, 38, '00035', 'Riesgo de lesión', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (210, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (211, 38, '00245', 'Riesgo de lesión corneal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (212, 38, '00250', 'Riesgo de lesión del tracto urinario', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (213, 38, '00087', 'Riesgo de lesión postural perioperatoria', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (214, 38, '00220', 'Riesgo de lesión térmica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (215, 38, '00031', 'Limpieza ineficaz de las vías aéreas', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (215, 124);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (216, 38, '00156', 'Riesgo de muerte súbita del lactante', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (217, 38, '00246', 'Riesgo de retraso en la recuperación quirúrgica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (218, 38, '00100', 'Retraso en la recuperación quirúrgica', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (218, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (218, 53);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (218, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (219, 38, '00206', 'Riesgo de sangrado', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (220, 38, '00261', 'Riesgo de sequedad bucal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (221, 38, '00219', 'Riesgo de sequedad ocular', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (222, 38, '00205', 'Riesgo de shock', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (222, 55);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (223, 38, '00038', 'Riesgo de traumatismo físico', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (224, 38, '00213', 'Riesgo de traumatismo vascular', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (225, 38, '00304', 'Riesgo de lesión por presión en el adulto', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (226, 38, '00312', 'Lesión por presión en el adulto ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (227, 38, '00286', 'Riesgo de lesión por presión en el niño ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (228, 38, '00313', 'Lesión por presión en el niño ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (229, 38, '00288', 'Riesgo de lesión por presión en el neonato ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (230, 38, '00287', 'Lesión por presión en el neonato ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (231, 38, '00277', 'Autocuidado ineficaz del ojo seco ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (232, 38, '00320', 'Lesión compleja del pezón-areola ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (233, 38, '00321', 'Riesgo de lesión compleja del pezón-areola ', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (234, 39, '00139', 'Riesgo de automutilación', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (234, 1);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (234, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (235, 39, '00151', 'Automutilación', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (235, 1);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (235, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (236, 39, '00272', 'Riesgo de mutilación genital femenina', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (237, 39, '00289', 'Riesgo de conducta suicida', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (237, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (238, 39, '00140', 'Riesgo de violencia autodirigida', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (238, 1);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (239, 39, '00138', 'Riesgo de violencia dirigida a otros', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (239, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (240, 40, '00180', 'Riesgo de contaminación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (241, 40, '00181', 'Contaminación', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (241, 119);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (242, 40, '00037', 'Riesgo de intoxicación', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (243, 40, '00265', 'Riesgo de lesión ocupacional', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (244, 41, '00218', 'Riesgo de reacción adversa a medios de contraste yodados', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (245, 41, '00217', 'Riesgo de respuesta alérgica', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (246, 41, '00042', 'Riesgo de respuesta alérgica al látex', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (247, 42, '00007', 'Hipertermia', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (247, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (248, 42, '00253', 'Riesgo de hipotermia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (249, 42, '00006', 'Hipotermia', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (250, 42, '00254', 'Riesgo de hipotermia perioperatoria', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (251, 42, '00274', 'Riesgo de termorregulación ineficaz', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (252, 42, '00008', 'Termorregulación ineficaz', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (252, 55);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (252, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (253, 42, '00280', 'Hipotermia neonatal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (254, 42, '00282', 'Riesgo de hipotermia neonatal', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (255, 43, '00214', 'Disconfort', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (255, 22);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (255, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (256, 43, '00183', 'Disposición para mejorar el confort', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (257, 43, '00132', 'Dolor agudo', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (257, 22);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (257, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (257, 53);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (257, 54);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (257, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (258, 43, '00133', 'Dolor crónico', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (258, 22);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (258, 29);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (258, 53);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (258, 62);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (258, 2552);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (259, 43, '0026', 'Dolor de parto', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 204);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 219);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 1130);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 1354);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 1737);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 1740);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 1784);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 2023);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 3525);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 3532);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 3535);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4266);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4553);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4568);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4570);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4572);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4574);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4576);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4578);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4579);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4597);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4726);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4838);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4888);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 4999);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 5189);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 5244);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 5292);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 5468);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 5507);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 5681);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6085);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6118);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6158);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6231);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6238);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6313);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 6377);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7253);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7315);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7342);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7407);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7412);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7439);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7571);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7746);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7853);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 7906);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (259, 8058);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (260, 43, '00134', 'Náuseas', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (260, 22);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (260, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (261, 43, '00255', 'Síndrome de dolor crónico', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (262, 44, '00214', 'Disconfort', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (262, 22);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (262, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (263, 44, '00183', 'Disposición para mejorar el confort', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (264, 45, '00053', 'Aislamiento social', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (265, 45, '00214', 'Disconfort', '1', FALSE);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (265, 22);
insert into estandares.nanda_nic_nanda_diagnostico(nanda_fk, nic_fk) values (265, 62);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (266, 45, '00183', 'Disposición para mejorar el confort', '1', FALSE);
insert  into  estandares.nanda_diagnostico(id, clase_fk, codigo, nombre, version, deleted) values (267, 45, '00054', 'Riesgo de soledad', '1', FALSE);
